### PR TITLE
lang pt.json

### PR DESCRIPTION
**Pull request by ViPeR5000**

### CODE REVIEW

**Comment by vingerha** [comment]
Hi, thanks a lot. I am not going to test this assuming you have it working :)

**Comment by ViPeR5000** [comment]
> Hi, thanks a lot. I am not going to test this assuming you have it working :)

please test.

**Comment by vingerha** [comment]
Well, I did not need to test it as it crashed during validation of the json file. 
Do you have it working with you?

**Comment by vingerha** [comment]
Best you compare the en.json with the pt.json (e.g. notepad++) and rework it until you have it working locally with you.
I believe it is missing at least a closing accolade ']'  at the end

**Pull request merged**
